apiVersion: v1
kind: Secret
metadata:
  name: letsencrypt-accountkey-secret
type: Opaque
data:
  letsencrypt-accountkey-secret: {{ .Values.letsencrypt.accountKey | required "letsencrypt.accountKey must be set" | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: route53-accessKeyID-secret
type: Opaque
data:
  route53-accessKeyID-secret: {{ .Values.route53.accessKeyID | required "route53.accessKeyID  must be set" | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: route53-secretAccessKey-secret
type: Opaque
data:
  route53-secretAccessKey-secret: {{ .Values.route53.secretAccessKey | required "route53.secretAccessKey must be set" | b64enc }}