#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: obebete/cyberchef
  # -- image tag
  # @default -- chart.appVersion
  tag: 
  # -- image pull policy
  pullPolicy: Always

# -- environment variables
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC

# -- Configures service settings for the chart.
# @default -- See the [docs](https://github.com/k8s-at-home/library-charts/blob/main/charts/stable/common/README.md)
service:
  main:
    ports:
      http:
        port: 8000

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/proxy-next-upstream: "http_429"
      nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "3"
    hosts:
      - host: chef.priv.au
        paths:
          - path: /
            pathType: Prefix
    ingressClassName: ""
    tls:
      - hosts:
          - chef.priv.au
        secretName: privau-tls

persistence: {}
