image:
  repository: registry.k8s.io/dns/k8s-dns-node-cache
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

config:
  # Internal k8s DNS domain
  dnsDomain: "cluster.local"

  # Main coredns service (kube-dns) ip, used on iptables-mode.
  dnsServer: "10.43.0.10"

  # Virtual IP to be used by ipvs mode, to be used as --cluster-dns, must not collide.
  localDns: "169.254.20.25"

  # Set communication protocol. Options are `prefer_udp` or `force_tcp`
  commProtocol: "force_tcp"

  # Port used for the health endpoint
  healthPort: 8080

  setupInterface: true

  setupIptables: true

  skipTeardown: false


nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created.
  create: true

securityContext:
  capabilities:
    add:
    - NET_ADMIN

resources:
  requests:
    cpu: 25m
    memory: 128Mi
  limits:
    memory: 128Mi

prometheusScraping:
  enabled: true