apiVersion: v2
appVersion: latest
name: searxng
version: 1.0.0
keywords:
  - searxng
sources:
  - https://hub.docker.com/r/vojkovic/searxng/
dependencies:
  - name: application
    repository: https://stakater.github.io/stakater-charts
    version: 2.1.18
    alias: searxng
  - name: redis
    version: 1.1.3
    repository: https://charts.pascaliske.dev
    condition: redis.enabled
