searxng:
  applicationName: "searxng"

  rbac:
    serviceAccount:
      enabled: false
      name: "tiny"

  deployment:
    enabled: true
    securityContext:
      runAsUser: 10000
      runAsGroup: 10000
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
    image:
      repository: vojkovic/searxng
      tag: production
      pullPolicy: Always
    startupProbe:
      enabled: true
      failureThreshold: 5
      periodSeconds: 10
      timeoutSeconds: 60
      initialDelaySeconds: 5
      httpGet:
        path: /healthz
        port: 8080

    readinessProbe:
      enabled: true
      failureThreshold: 3
      periodSeconds: 60
      timeoutSeconds: 60
      httpGet:
        path: /healthz
        port: 8080

    livenessProbe:
      enabled: true
      failureThreshold: 3
      periodSeconds: 60
      timeoutSeconds: 60
      httpGet:
        path: /healthz
        port: 8080

    ports:
    - containerPort: 8080
      name: http
      protocol: TCP

    ingress:
      enabled: false
      
  env:
    SEARXNG_SECRET: "changedsecret"
    LIMITER: true
    REDIS_URL: "redis://redis.searxng.svc.cluster.local"
    PRIVACYPOLICY: "https://priv.au/privacy/"
    IMAGE_PROXY: "true"
    CONTACT: "https://vojk.au/"
    SEARCH_DEFAULT_LANG: "en"
    SEARCH_ENGINE_ACCESS_DENIED: 60
    PUBLIC_INSTANCE: true
  
redis:
  enabled: true
  persistentVolumeClaim:
    create: false