#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: searxng/searxng
  # -- image tag
  tag: latest
  # -- image pull policy
  pullPolicy: Always

image:
  repository: unixfox/searx-custom
  tag: latest
  pullPolicy: Always
replicaCount: 4
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 50
nodeSelector: {}
affinity: {}
resources: {}
  #requests:
  #  cpu: 100m
  #  memory: 64Mi
  #limits:
  #  cpu: 800m
  #  memory: 512Mi

# Explanation about each environment variables here:
# https://docs.searxng.org/admin/installation-docker.html#command-line
env:
  INSTANCE_NAME: "SearXNG"
  BASE_URL: "http://localhost:8080/"
  AUTOCOMPLETE: "false"
  # MORTY_URL: "http://morty:8080"
  # MORTY_KEY: "mysecretkey"
  # BIND_ADDRESS: "0.0.0.0:8080"

controller:
  strategy: "RollingUpdate"

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

searxng:
  config:
    use_default_settings: true
    server:
      secret_key: pleasechangeme
    # Uncomment when using the builtin rate limiter
    # See https://docs.searxng.org/src/searx.plugins.limiter.html#limiter-plugin
    # server.limiter: true
    # redis.url: redis://@searxng-redis:6379/0

probes:
  readiness:
    custom: true
    spec:
      httpGet:
        path: /healthz
        port: 8080
  liveness:
    custom: true
    spec:
      httpGet:
        path: /healthz
        port: 8080
  startup:
    custom: true
    spec:
      httpGet:
        path: /healthz
        port: 8080

# Enable when using searxng builtin rate limiter
# Values: https://github.com/pascaliske/helm-charts/tree/master/charts/redis
redis:
  enabled: false
  