searxng:
  deployment:
    replicas: 5
  ingress:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/proxy-next-upstream: "http_429"
      nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "3"
    hosts:
      -  # -- Host address. Helm template can be passed.
        host: priv.au
        ## Configure the paths for the host
        paths:
          -  # -- Path.  Helm template can be passed.
            path: /
            # -- Ignored if not kubeVersion >= 1.14-0
            pathType: Prefix
            service:
              # -- Overrides the service name reference for this path
              name:
              # -- Overrides the service port reference for this path
              port:
    # -- Configure TLS for the ingress. Both secretName and hosts can process a Helm template.
    tls:
      - secretName: privau-tls
        hosts:
          - priv.au

